# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GarbageAI-Camera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GarbageAI-Camera
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

end
